### ISSUE TITLE
Please install root dictionary "dict_rdict.pcm" into folder "lib" 

### ISSUE THREAD

**Issue by shaojunlu** [lcfiplus/LCFIPlus#17]
I have not permission to fork your repository, so could not create a pull request.
I try to report this issue here:

Issue: To avoid this error information during reconstruction:
"Error in <TCling::RegisterModule>: cannot find dictionary module dict_rdict.pcm"

Solution: Please install your "dict_rdict.pcm" into folder "lib".

Inorder to do so: you may update the CMakeList.txt by adding one line "INSTALL(FILES ${ROOT_DICT_OUTPUT_DIR}/dict_rdict.pcm DESTINATION lib)"

Here is the detail with git diff:

diff --git a/CMakeLists.txt b/CMakeLists.txt
index f87ee01..f384e52 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -58,6 +58,7 @@ SET( ROOT_DICT_INPUT_HEADERS
 )
 SET( ROOT_DICT_INCLUDE_DIRS ${Marlin_INCLUDE_DIRS} )
 GEN_ROOT_DICT_SOURCES( dict.cc )
+INSTALL(FILES ${ROOT_DICT_OUTPUT_DIR}/dict_rdict.pcm DESTINATION lib)
 LIST(APPEND library_sources ${ROOT_DICT_OUTPUT_SOURCES} )
 
 SET( binary_sources ./src/Driver.cc ./src/EventNavigator.cc )

**Comment by jstrube** [comment]
This is the first time I'm encountering this problem: What prevents you from forking the directory?
I'll add your patch, but if there's something we should be doing to resolve your forking problems, please let us know.
