### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by bogdanmishchenko** [lcfiplus/LCFIPlus#28]
Dear LCFIPLus developers, 
I have encountered memory allocation (malloc) error  problem while running train.xml ("MyLcfiplusProcessor") . I have used different ilcsoft versions (/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/ and /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-03/). You can find steering file what I have used and log file attached in zip archive. 
[Files_train.zip](https://github.com/lcfiplus/LCFIPlus/files/1156135/Files_train.zip)

**Comment by andresailer** [comment]
Your zip file seems to be corrupted

**Comment by bogdanmishchenko** [comment]
[Files_train_new.zip](https://github.com/lcfiplus/LCFIPlus/files/1156161/Files_train_new.zip)

**Comment by bogdanmishchenko** [comment]
[zip_train.zip](https://github.com/lcfiplus/LCFIPlus/files/1156182/zip_train.zip)

**Comment by andresailer** [comment]
Does this also happen if you use the LCFIPlus library that is part of the v01-19-03 release instead of your own?

**Comment by bogdanmishchenko** [comment]
I have noticed this feature once I started using LCFIPlus, since then I have started taking out ilcsoft LCFIPlus release in library path. 
Here is my library path, which I have used:
/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/MarlinDD4hep/v00-04/lib/libMarlinDD4hep.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/DDMarlinPandora/v00-06/lib/libDDMarlinPandora.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/MarlinReco/v01-18/lib/libMarlinReco.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/PandoraAnalysis/v01-02-01/lib/libPandoraAnalysis.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/LCFIVertex/v00-07-03/lib/libLCFIVertex.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/CEDViewer/v01-13/lib/libCEDViewer.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/Overlay/v00-17/lib/libOverlay.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/MarlinFastJet/v00-04/lib/libMarlinFastJet.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/LCTuple/v01-07/lib/libLCTuple.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/MarlinKinfit/v00-05/lib/libMarlinKinfit.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/MarlinTrkProcessors/v02-06/lib/libMarlinTrkProcessors.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/MarlinKinfitProcessors/v00-03/lib/libMarlinKinfitProcessors.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/ILDPerformance/v01-02/lib/libILDPerformance.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/Clupatra/v01-00/lib/libClupatra.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/Physsim/v00-04/lib/libPhyssim.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/ForwardTracking/v01-11/lib/libForwardTracking.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/ConformalTracking/v01-02/lib/libConformalTracking.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/LICH/v00-01/lib/libLICH.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/MarlinTPC/v01-02/lib/libMarlinTPC.so:/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-02/Garlic/v3.0.4/lib/libGarlic.so:/afs/phas.gla.ac.uk/user/b/bogdanm/public_ppe/Flavour_Tagging/LCFIPlus_10_06_17/LCFIPlus/lib/libLCFIPlus.so

**Comment by bogdanmishchenko** [comment]
I have used 10k for each b-jet, c-jet, light jet. For two categories (A (Category 1- number of vertices=0), B(Category 2- number of vertices=1) ) it works fine. However for Category 3 and Category 4 it crashes.

**Comment by jstrube** [comment]
Hmm strange. Those are the categories "2-vtx" and "1 vtx + 1 track with large d0", I think.

The first thing to try is what Andre suggests: Use v01-19-03. If that doesn't work, try to compile LCFIPlus from the github checkout.
Is that better?

**Comment by bogdanmishchenko** [comment]
Dear Jan, Andre ! So actually I have tried to use v01-19-03( I have adjusted   reconstruction code for it  ) and run  simulation/reconstruction + vertexjet+ train and it still crashes if I use more than two categories( "1 vtx + 1" and "2-vtx"). The last  time I have checked out LCFIPlus was on 15th July. I have also noticed 
there is new patch for 01-19-03.p01. Is it worth to try this one ?

**Comment by jstrube** [comment]
I'm not aware of recent LCFIPlus changes, so I don't think the patch will be better for you.
We'll have to look into the categories in more detail...

**Comment by bogdanmishchenko** [comment]
I am wondering if anybody can point me out to the  original Z-pole files (sqrt(s)=91.2 GeV), because I have tried Higgs bb-bar, light jet(H->bbbar, light jet) samples and it worked for all categories 4 categories. So, I guess problem was that samples of single b,c,u-jets doesn't have 2 vertices, while Z->qq,bb, cc have it.

**Comment by jstrube** [comment]
Hmm. It's true that single jets are unphysical samples, so you might get answers that are hard to interpret, but there shouldn't be a crash due to number of vertices in the events. e+ e- --> nu nu should be just fine. Let's leave this bug report open for this reason.

I don't have any 91 GeV samples handy. What do you think they would give you that you can't get from the samples that you have?

**Comment by bogdanmishchenko** [comment]
Thanks for reply, Jan! 
I meant weight files (*.root)for 4 categories and (*.xml, *.C), which can be used as input for  flavour tag(flavourtag.xml), because now I have only two pair of files for two first categories. Hence, I expect performance to be better.
So where I can obtain e+e--->nu nu files ?
I will ask Dan and Aidan on Monday.

**Comment by jstrube** [comment]
Sorry, misunderstanding: e+e- --> nu nu doesn't have any vertices, so it's not useful for your training.
However, even though it doesn't have any vertices, it's a legitimate physics process and should not crash LCFIPlus.

I don't quite understand what's missing. You should be able to extract the training for all four categories from the three processes you have: H --> bb, cc, gg. 
Is that not the case?
I doubt that training on 91 GeV samples will help you with the training. We will never run the ILC at 91 GeV, so I'd prefer to get this working on physics samples. What exactly is missing?

**Comment by bogdanmishchenko** [comment]
I have got physics samples( H-->bb,cc,gg). However, I have got some problems with compiling DD4hep in order to change collection name.

**Comment by jstrube** [comment]
@bogdanmishchenko I've started on changes to DD4hep and lcgeo to allow setting the collection name to something else.
I've also had some compilation issues, though.
Let's hope this works and makes it into a new release soon.

**Comment by bogdanmishchenko** [comment]
Thanks a lot ! Hopefully it work out !
