### ISSUE TITLE
Replace "." with "_" in parameter names

### ISSUE THREAD

**Issue by jstrube** [lcfiplus/LCFIPlus#3]
The following is a feature request from Philipp Roloff.
I think implementing this change makes a lot of sense. Any reason not to do it?

-----Original Message-----
From: Philipp Roloff philipp.roloff@cern.ch
Date: Wednesday, July 8, 2015 at 04:39
Subject: One more LCFIPlus suggestion

Dear all,

I have a suggestion on the LCFIPlus parameter names: since points are
used in the LCFIPlus parameter names, it is not possible to overwrite
the LCFIPlus parameters on the command line when running Marlin. This is
sometimes useful, for example in ILCDIRAC user jobs.

I'm using a modified version of LCFIPlus where the points in the
relevant parameters are replaced by another character, e.g.:

string outputFilename =
param->get("MakeNtuple_OutputRootFileName",string("flavtag.root"));

instead of:

string outputFilename =
param->get("MakeNtuple.OutputRootFileName",string("flavtag.root"));

I think it would be nice to replace the points in the parameter names to
allow the usage of Marlin command line arguments for all LCFIPlus
parameters.

Thanks a lot in advance,
    Philipp

**Comment by suehara** [comment]
It's OK, but I'd rather avoid an underscore (I have an impression of "temporal" or "internal" in it). How about a colon(:)?

**Comment by jstrube** [comment]
I agree that leading underscores like_thisIsAName look strange, but underscores_within_function_names are very common replacements of spaces, dashes or other special characters.
I'd be happy with a colon as well. Have you tried whether this works in Marlin?

**Comment by andresailer** [comment]
This problem is solved in the next Marlin release. Parameter names may contain dots, so no changes in LCFIplus are necessary
