### ISSUE TITLE
https://github.com/iLCSoft/LCFIPlus/pull/3 example to use DD4hep to access BField.

### ISSUE THREAD

**Issue by shaojunlu** [lcfiplus/LCFIPlus#30]
This MarlinProcessor is used in ILD standard reconstruction chain.
ILD is going to get rid of gear in the reconstruction, and to access detector data directly from DD4hep, this is one example solution for your MarlinProcessor.
https://github.com/iLCSoft/LCFIPlus/pull/3

I could not fork your repository, so could not generate pull request directly to here.
I fork it from ilcsoft, and generate a PR.

Would you please download from ilcsoft and update your repository?

Thank you very much!

**Comment by shaojunlu** [comment]
Dear LCFIPlus administrator,

Please inform Frank when you have done this update. He wish that this ilcsoft release will include your MarlinProcessor.

Thank you very much!

**Comment by petricm** [comment]
iLCSoft/LCFIPlus is a fork of lcfiplus/LCFIPlus so you do not need to fork lcfiplus/LCFIPlus but only add it as a remote and rebase your changes to lcfiplus/LCFIPlus, then you can do a PR.

I am not sure but I don't think is't possible to have at the same time a fork of iLCSoft/LCFIPlus and lcfiplus/LCFIPlus because they represent the same "development tree"

**Comment by tomohikosan** [comment]
I'll be happy to merge the PR if you could create one -- we have also just granted write access to @gaede and @andresailer so they can do this as well to test if the write permissions work

**Comment by gaede** [comment]
just created https://github.com/lcfiplus/LCFIPlus/pull/31 - can merge if approved ...

**Comment by tomohikosan** [comment]
@gaede I just added more rights -- could you please test if you're able to merge now?

**Comment by andresailer** [comment]
I see the merge button here now. Can we change the "merging" to be rebase only, like we do in all the other iLCSoft packages? I.e. in settings only "allow rebase merging". 
This gives a nice linear history

**Comment by gaede** [comment]
Done.
