### ISSUE TITLE
TMVA Training not optimal for ROOT 5.34

### ISSUE THREAD

**Issue by jstrube** [lcfiplus/LCFIPlus#4]
The change of some defaults for TMVA in ROOT 5.34 means that the training parameters provided by default are no longer optimal. They were OK in ROOT 5.28.
For the next production release, we should investigate whether to target ROOT 5.34 or ROOT 6 with the training parameters (if there's a difference).

**Comment by tomohikosan** [comment]
ROOT 6 is now required; performance has been checked using ILD samples
