### ISSUE TITLE
PrimaryVertexFinder.TrackMaxInnermostHitRadius parameter obsolete?

### ISSUE THREAD

**Issue by andresailer** [lcfiplus/LCFIPlus#47]
In this commit  https://github.com/lcfiplus/LCFIPlus/commit/0c961178e590f32717b53e081522c3d0a16f2db7#diff-d5939a2753951ddbb81d7c60554d505c
the parsing of the PrimaryVertexFinder.TrackMaxInnermostHitRadius parameter was removed. Was that intentional? I see this parameter still in many steering files, so I am wondering if the parsing should be added again, of if we can remove that parameter from our steering file.

**Comment by tomohikosan** [comment]
Yes, PrimaryVertexFinder.TrackMaxInnermostHitRadius is obsolete and can be removed from steering files (but leaving it does no harm).
