### ISSUE TITLE
Zenodo Link for LCFIPlus

### ISSUE THREAD

**Issue by jstrube** [lcfiplus/LCFIPlus#5]
It might be nice to have a link to a Zenodo entry for each release.
https://zenodo.org/
This creates a unique DOI entry for a release, so it's citeable in scientific papers. (Of course the arXiv or NIM A paper should also be cited, but the Zenodo link is easy to update for new releases).

What do you think?

**Comment by tomohikosan** [comment]
I think this is a neat idea and gives a way to credit all the contributors.

**Comment by jstrube** [comment]
Done! I'm adding a link to the readme.
